algo-morogo/algo_1th

- jiho/0026-remove-duplicates-from-sorted-array/0026-remove-duplicates-from-sorted-array.ts
- jiho/0026-remove-duplicates-from-sorted-array/README.md
- jiho/0122-best-time-to-buy-and-sell-stock-ii/0122-best-time-to-buy-and-sell-stock-ii.ts
- jiho/0122-best-time-to-buy-and-sell-stock-ii/README.md
- jiho/0136-single-number/0136-single-number.ts
- jiho/0136-single-number/README.md
- jiho/0189-rotate-array/0189-rotate-array.ts
- jiho/0189-rotate-array/README.md
- jiho/0217-contains-duplicate/0217-contains-duplicate.ts
- jiho/0217-contains-duplicate/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 지호 / 9월 3주차 / 5문제

- YeongseoYoon/0026-remove-duplicates-from-sorted-array/0026-remove-duplicates-from-sorted-array.js
- YeongseoYoon/0026-remove-duplicates-from-sorted-array/README.md
- YeongseoYoon/0122-best-time-to-buy-and-sell-stock-ii/0122-best-time-to-buy-and-sell-stock-ii.js
- YeongseoYoon/0122-best-time-to-buy-and-sell-stock-ii/README.md
- YeongseoYoon/0136-single-number/0136-single-number.js
- YeongseoYoon/0136-single-number/README.md
- YeongseoYoon/0189-rotate-array/0189-rotate-array.js
- YeongseoYoon/0189-rotate-array/README.md
- YeongseoYoon/0217-contains-duplicate/0217-contains-duplicate.js
- YeongseoYoon/0217-contains-duplicate/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 영서 / 9월 3주차 / 5문제

- jihyeon/0026-remove-duplicates-from-sorted-array/0026-remove-duplicates-from-sorted-array.js
- jihyeon/0026-remove-duplicates-from-sorted-array/README.md
- jihyeon/0122-best-time-to-buy-and-sell-stock-ii/0122-best-time-to-buy-and-sell-stock-ii.js
- jihyeon/0122-best-time-to-buy-and-sell-stock-ii/README.md
- jihyeon/LeetCode/Easy/0136-single-number/0136-single-number.js
- jihyeon/LeetCode/Easy/0136-single-number/README.md
- jihyeon/LeetCode/Easy/0217-contains-duplicate/0217-contains-duplicate.js
- jihyeon/LeetCode/Easy/0217-contains-duplicate/README.md
- jihyeon/LeetCode/Medium/0189-rotate-array/0189-rotate-array.js
- jihyeon/LeetCode/Medium/0189-rotate-array/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 지현 / 9월 3주차 / 5문제

- tooth-is-silver/0026-remove-duplicates-from-sorted-array/0026-remove-duplicates-from-sorted-array.js
- tooth-is-silver/0026-remove-duplicates-from-sorted-array/README.md
- tooth-is-silver/0122-best-time-to-buy-and-sell-stock-ii/0122-best-time-to-buy-and-sell-stock-ii.js
- tooth-is-silver/0122-best-time-to-buy-and-sell-stock-ii/README.md
- tooth-is-silver/0136-single-number/0136-single-number.js
- tooth-is-silver/0136-single-number/README.md
- tooth-is-silver/0189-rotate-array/0189-rotate-array.js
- tooth-is-silver/0189-rotate-array/README.md
- tooth-is-silver/0217-contains-duplicate/0217-contains-duplicate.js
- tooth-is-silver/0217-contains-duplicate/README.md
- 어떤 부분이 어려웠는지
**0026-remove-duplicates-from-sorted-array**
영어 독해가 너무 어려웠다...
**122. Best Time to Buy and Sell Stock II**
그리디 접근법인지 몰라서 엄청 해멨음
**0026-remove-duplicates-from-sorted-array**
처음에 new Set으로 접근하려고 했는데 새로운 배열을 만들어버려서 fail. 다시 원래 작성되어있던 for문을 사용해서 시도했음
**122. Best Time to Buy and Sell Stock II**
최소 값과 최대값을 비교해야하나..? 최대 값을 미리 구해야하나...? 알고보니 단순하게 수학적으로 접근해야하는 거였다
- 결국 해결하게 된 계기
**0026-remove-duplicates-from-sorted-array**
하나씩 비교해서 **원본 배열**에 수정해서 넣고 따로 result로 카운트 해서 최종 값을 return해줌
**122. Best Time to Buy and Sell Stock II**
접근 방법을 참고해서 앞/뒤 비교 후 차액을 result에 더해줘서 반환해줌
---
그리드 접근법
> 가은 / 9월 3주차 / 5문제

- changyu/0026-remove-duplicates-from-sorted-array/0026-remove-duplicates-from-sorted-array.ts
- changyu/0026-remove-duplicates-from-sorted-array/README.md
- changyu/0122-best-time-to-buy-and-sell-stock-ii/0122-best-time-to-buy-and-sell-stock-ii.ts
- changyu/0122-best-time-to-buy-and-sell-stock-ii/README.md
- changyu/0136-single-number/0136-single-number.ts
- changyu/0136-single-number/README.md
- changyu/0189-rotate-array/0189-rotate-array.ts
- changyu/0189-rotate-array/README.md
- changyu/0217-contains-duplicate/0217-contains-duplicate.ts
- changyu/0217-contains-duplicate/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 찬규 / 9월 3주차 / 5문제

- 0026-remove-duplicates-from-sorted-array/0026-remove-duplicates-from-sorted-array.js
- 0026-remove-duplicates-from-sorted-array/README.md
- 0122-best-time-to-buy-and-sell-stock-ii/0122-best-time-to-buy-and-sell-stock-ii.js
- 0122-best-time-to-buy-and-sell-stock-ii/README.md
- 0136-single-number/0136-single-number.js
- 0136-single-number/README.md
- 0189-rotate-array/0189-rotate-array.js
- 0189-rotate-array/README.md
- 0217-contains-duplicate/0217-contains-duplicate.js
- 0217-contains-duplicate/README.md
- 어떤 부분이 어려웠는지
영어로 풀어보는건 처음이라 머리가 안돌아가네요
- 결국 해결하게 된 계기
---
> 진석 / 9월 3주차 / 5문제  🦍

- mingi/0026-remove-duplicates-from-sorted-array/0026-remove-duplicates-from-sorted-array.js
- mingi/0026-remove-duplicates-from-sorted-array/README.md
- mingi/0122-best-time-to-buy-and-sell-stock-ii/0122-best-time-to-buy-and-sell-stock-ii.js
- mingi/0122-best-time-to-buy-and-sell-stock-ii/README.md
- mingi/0136-single-number/0136-single-number.js
- mingi/0136-single-number/README.md
- mingi/0189-rotate-array/0189-rotate-array.js
- mingi/0189-rotate-array/README.md
- mingi/0217-contains-duplicate/0217-contains-duplicate.js
- mingi/0217-contains-duplicate/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
rotate-array 문제 풀이
```typescript
/**
* @param {number[]} nums
* @param {number} k
* @return {void} Do not return anything, modify nums in-place instead.
*/
var rotate = function(nums, k) {
for(let i=0;i<k;i++){
const lastElement = nums.pop();
nums.splice(0, 0, lastElement);
}
return nums;
};
```
이였는데 시간복잡도가 O(k * n) 나오면서 시간초과 발생.
이 후 코드 수정 시간복잡도 : O(n) 으로 바꾸기.	
1. 실제로 회전해야 할 횟수를 계산. 배열을 n번 회전하면 제자리로 돌아오므로, k를 nums.length로 나눈 나머지(k % nums.length) 만큼만 회전시킴
2. 배열의 끝에서 k개의 요소를 splice로 잘라내기
3. 잘라낸 요소들을 unshift(O(n))와 스프레드 문법(...)을 사용해 배열의 맨 앞에 붙여 넣기 (unshift는 배열의 맨 앞에 추가하는 역할)
```typescript
var rotate = function(nums, k) {
const n = nums.length;
k = k % n;
if (k === 0) {
return; 
}
const …
```
> 민기 / 9월 3주차 / 5문제

- jungseokheo/0001-two-sum/0001-two-sum.js
- jungseokheo/0001-two-sum/README.md
- jungseokheo/0036-valid-sudoku/0036-valid-sudoku.js
- jungseokheo/0036-valid-sudoku/README.md
- jungseokheo/0066-plus-one/0066-plus-one.js
- jungseokheo/0066-plus-one/README.md
- jungseokheo/0283-move-zeroes/0283-move-zeroes.js
- jungseokheo/0283-move-zeroes/README.md
- jungseokheo/0350-intersection-of-two-arrays-ii/0350-intersection-of-two-arrays-ii.js
- jungseokheo/0350-intersection-of-two-arrays-ii/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 정석 / 9월 4주차 / 5문제 🧦🧦🧦🧦🧦

- tooth-is-silver/0001-two-sum/0001-two-sum.js
- tooth-is-silver/0001-two-sum/README.md
- tooth-is-silver/0036-valid-sudoku/0036-valid-sudoku.js
- tooth-is-silver/0036-valid-sudoku/README.md
- tooth-is-silver/0066-plus-one/0066-plus-one.js
- tooth-is-silver/0066-plus-one/README.md
- tooth-is-silver/0283-move-zeroes/0283-move-zeroes.js
- tooth-is-silver/0283-move-zeroes/README.md
- tooth-is-silver/0350-intersection-of-two-arrays-ii/0350-intersection-of-two-arrays-ii.js
- tooth-is-silver/0350-intersection-of-two-arrays-ii/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 가은 / 9월 4주차 / 5문제

- YeongseoYoon/0001-two-sum/0001-two-sum.js
- YeongseoYoon/0001-two-sum/README.md
- YeongseoYoon/0036-valid-sudoku/0036-valid-sudoku.js
- YeongseoYoon/0036-valid-sudoku/README.md
- YeongseoYoon/0066-plus-one/0066-plus-one.js
- YeongseoYoon/0066-plus-one/README.md
- YeongseoYoon/0283-move-zeroes/0283-move-zeroes.js
- YeongseoYoon/0283-move-zeroes/README.md
- YeongseoYoon/0350-intersection-of-two-arrays-ii/0350-intersection-of-two-arrays-ii.js
- YeongseoYoon/0350-intersection-of-two-arrays-ii/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 영서 / 9월 4주차 / 5문제

- hyojin/0001-two-sum/0001-two-sum.js
- hyojin/0001-two-sum/README.md
- hyojin/0036-valid-sudoku/0036-valid-sudoku.js
- hyojin/0036-valid-sudoku/README.md
- hyojin/0066-plus-one/0066-plus-one.js
- hyojin/0066-plus-one/README.md
- hyojin/0283-move-zeroes/0283-move-zeroes.js
- hyojin/0283-move-zeroes/README.md
- hyojin/0350-intersection-of-two-arrays-ii/0350-intersection-of-two-arrays-ii.js
- hyojin/0350-intersection-of-two-arrays-ii/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 효진 / 9월 4주차 / 5문제

- uichan/0001-two-sum/0001-two-sum.ts
- uichan/0001-two-sum/README.md
- uichan/0036-valid-sudoku/0036-valid-sudoku.ts
- uichan/0036-valid-sudoku/README.md
- uichan/0066-plus-one/0066-plus-one.ts
- uichan/0066-plus-one/README.md
- uichan/0189-rotate-array/0189-rotate-array.ts
- uichan/0283-move-zeroes/0283-move-zeroes.ts
- uichan/0283-move-zeroes/README.md
- uichan/0350-intersection-of-two-arrays-ii/0350-intersection-of-two-arrays-ii.ts
- uichan/0350-intersection-of-two-arrays-ii/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 의찬 / 9월 4주차 / 5문제

- changyu/0001-two-sum/0001-two-sum.ts
- changyu/0001-two-sum/README.md
- changyu/0036-valid-sudoku/0036-valid-sudoku.ts
- changyu/0036-valid-sudoku/README.md
- changyu/0066-plus-one/0066-plus-one.ts
- changyu/0066-plus-one/README.md
- changyu/0283-move-zeroes/0283-move-zeroes.ts
- changyu/0283-move-zeroes/README.md
- changyu/0350-intersection-of-two-arrays-ii/0350-intersection-of-two-arrays-ii.ts
- changyu/0350-intersection-of-two-arrays-ii/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 찬규 / 9월 4주차 / 5문제

- jihyeon/LeetCode/Easy/0001-two-sum/0001-two-sum.js
- jihyeon/LeetCode/Easy/0001-two-sum/README.md
- jihyeon/LeetCode/Easy/0066-plus-one/0066-plus-one.js
- jihyeon/LeetCode/Easy/0066-plus-one/README.md
- jihyeon/LeetCode/Easy/0283-move-zeroes/0283-move-zeroes.js
- jihyeon/LeetCode/Easy/0283-move-zeroes/README.md
- jihyeon/LeetCode/Easy/0350-intersection-of-two-arrays-ii/0350-intersection-of-two-arrays-ii.js
- jihyeon/LeetCode/Easy/0350-intersection-of-two-arrays-ii/README.md
- jihyeon/LeetCode/Medium/0036-valid-sudoku/0036-valid-sudoku.js
- jihyeon/LeetCode/Medium/0036-valid-sudoku/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 지현 / 9월 4주차 / 5문제

- jinseok/0001-two-sum/0001-two-sum.js
- jinseok/0001-two-sum/README.md
- jinseok/0036-valid-sudoku/0036-valid-sudoku.js
- jinseok/0036-valid-sudoku/README.md
- jinseok/0066-plus-one/0066-plus-one.js
- jinseok/0066-plus-one/README.md
- jinseok/0283-move-zeroes/0283-move-zeroes.js
- jinseok/0283-move-zeroes/README.md
- jinseok/0350-intersection-of-two-arrays-ii/0350-intersection-of-two-arrays-ii.js
- jinseok/0350-intersection-of-two-arrays-ii/0350-intersection-of-two-arrays-iijinseok.js
- jinseok/0350-intersection-of-two-arrays-ii/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 진석 / 9월 4주차 / 5문제

- doeun/0001-two-sum/0001-two-sum.js
- doeun/0001-two-sum/README.md
- doeun/0036-valid-sudoku/0036-valid-sudoku.js
- doeun/0036-valid-sudoku/README.md
- doeun/0066-plus-one/0066-plus-one.js
- doeun/0066-plus-one/README.md
- doeun/0283-move-zeroes/0283-move-zeroes.js
- doeun/0283-move-zeroes/README.md
- doeun/0350-intersection-of-two-arrays-ii/0350-intersection-of-two-arrays-ii.js
- doeun/0350-intersection-of-two-arrays-ii/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 도은 / 9월 4주차 / 5문제

- tooth-is-silver/0007-reverse-integer/0007-reverse-integer.js
- tooth-is-silver/0007-reverse-integer/README.md
- tooth-is-silver/0048-rotate-image/0048-rotate-image.js
- tooth-is-silver/0048-rotate-image/README.md
- tooth-is-silver/0344-reverse-string/0344-reverse-string.js
- tooth-is-silver/0344-reverse-string/README.md
- tooth-is-silver/0387-first-unique-character-in-a-string/0387-first-unique-character-in-a-string.js
- tooth-is-silver/0387-first-unique-character-in-a-string/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 가은 / 9월 5주차, 10월 1주차 / 4문제

- yuyeol/Easy/0344-reverse-string/0344-reverse-string.js
- yuyeol/Easy/0344-reverse-string/README.md
- yuyeol/Easy/0387-first-unique-character-in-a-string/0387-first-unique-character-in-a-string.js
- yuyeol/Easy/0387-first-unique-character-in-a-string/README.md
- yuyeol/Medium/0007-reverse-integer/0007-reverse-integer.js
- yuyeol/Medium/0007-reverse-integer/README.md
- yuyeol/Medium/0048-rotate-image/0048-rotate-image.js
- yuyeol/Medium/0048-rotate-image/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 유열/ 9월 4주차, 10월 1주차 / 4문제

- hyojin/0007-reverse-integer/0007-reverse-integer.js
- hyojin/0007-reverse-integer/README.md
- hyojin/0048-rotate-image/0048-rotate-image.js
- hyojin/0048-rotate-image/README.md
- hyojin/0344-reverse-string/0344-reverse-string.js
- hyojin/0344-reverse-string/README.md
- hyojin/0387-first-unique-character-in-a-string/0387-first-unique-character-in-a-string.js
- hyojin/0387-first-unique-character-in-a-string/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 효진/ 9월 5주차, 10월 1주차 / 4문제

- changjun/0007-reverse-integer/0007-reverse-integer.js
- changjun/0007-reverse-integer/README.md
- changjun/0048-rotate-image/0048-rotate-image.js
- changjun/0048-rotate-image/README.md
- changjun/0344-reverse-string/0344-reverse-string.js
- changjun/0344-reverse-string/README.md
- changjun/0387-first-unique-character-in-a-string/0387-first-unique-character-in-a-string.js
- changjun/0387-first-unique-character-in-a-string/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 창준 / 9월 5주차, 10월 1주차 / 4문제

- YeongseoYoon/0007-reverse-integer/0007-reverse-integer.js
- YeongseoYoon/0007-reverse-integer/README.md
- YeongseoYoon/0048-rotate-image/0048-rotate-image.js
- YeongseoYoon/0048-rotate-image/README.md
- YeongseoYoon/0344-reverse-string/0344-reverse-string.js
- YeongseoYoon/0344-reverse-string/README.md
- YeongseoYoon/0387-first-unique-character-in-a-string/0387-first-unique-character-in-a-string.js
- YeongseoYoon/0387-first-unique-character-in-a-string/README.md
- 어떤 부분이 어려웠는지
- 결국 해결하게 된 계기
---
> 영서 / 9월 5주차, 10월 1주차 / 4문제

- mingi/0007-reverse-integer/0007-reverse-integer.js
- mingi/0007-reverse-integer/README.md
- mingi/0048-rotate-image/0048-rotate-image.js
- mingi/0048-rotate-image/README.md
- mingi/0344-reverse-string/0344-reverse-string.js
- mingi/0344-reverse-string/README.md
- mingi/0387-first-unique-character-in-a-string/0387-first-unique-character-in-a-string.js
- mingi/0387-first-unique-character-in-a-string/README.md
- 어떤 부분이 어려웠는지
First Unique Character in a String 문제를 푸는데 문제는 이해가 갔는데, 뭔가 어떤식으로 접근해야할지 몰라서 조금 해맨거같다. 
이중 포문을 사용했는데, 시간 초과가 나왔고 시간 복잡도를 고려 안하고 풀어서 실패했다.
- 결국 해결하게 된 계기
결국 지피티의 도움을 받았고, 코드는 다음과 같고, 해설과정은 밑에 있다. 
```typescript
var firstUniqChar = function(s) {
const charCounts = {};
for (const char of s) {
charCounts[char] = (charCounts[char] || 0) + 1;
}
for (let i = 0; i < s.length; i++) {
const char = s[i];
if (charCounts[char] === 1) {
return i;
}
}
return -1;
};
```typescript
const charCounts = {};
```
이 첫 번째 단계의 목표는 문자열 s에 등장하는 모든 문자의 출현 횟수를 기록하는 것. 문자(키)와 그 출현 횟수(값)를 저장할 빈 객체(해시 맵)를 선언함.
```typescript
for (const char of s)
```
문자열 s의 처음부터 끝까지 각 문자를 순회
```typescript
charCounts[char] = (charCounts[char] || 0) + 1;
```
현재 문자가 charCounts에 이미 키로 존재한다면, 기존의 횟수에 1을 …
```
> 민기 / 9월 5주차, 10월 1주차 / 4문제
